### ISSUE TITLE
mixed queries with complex select still display erroneous schema

### ISSUE THREAD

**Issue by thibaultestier** [bfritscher/sqlexplorer#5]
### 1) schema de requête calculé initialement par la vue dans l'app sqlexplorer =

| sql                  | schema                       |
|-------------|---------------------|
| SELECT Faculte, Titre, Annee, SUM(Nombre) AS Total | Faculte, Total |

calculée par la vue avec le regexp_replace de la mort... :-)
```
 SELECT questions.id,
    questions.db_schema,
    questions.text,
    regexp_replace(regexp_replace("substring"(questions.sql, '^SELECT *(?:DISTINCT)? *(.*?) *FROM.*?'::text), 
                                  ', .*? AS '::text, 
                                  ', '::text, 
                                  'gs'::text ), 
                   '^.*? AS '::text, 
                   ''::text, 
                   'gs'::text ) AS schema
   FROM questions;
```

### 2) fix proposé pour la requête SQL de la vue:
```
CREATE OR REPLACE VIEW public.question_schemas
 AS
 SELECT questions.id,
    questions.db_schema,
    questions.text,
    regexp_replace(regexp_replace("substring"(questions.sql, '^SELECT *(?:DISTINCT)? *(.*?) *FROM.*?'::text),
                                  ',[^,]*? AS '::text,
                                  ', '::text,
                                  'gs'::text),
                   '^[^,]*? AS'::text,
                   ''::text,
                   'gs'::text) AS schema
   FROM questions;
``` 
résultat =
| sql                  | schema                       |
|-------------|---------------------|
| SELECT Faculte, Titre, Annee, SUM(Nombre) AS Total | Faculte, Titre, Annee, Total |

**Comment by bfritscher** [comment]
Merci, c'est mieux ! Idéalement, il faudrait une liste de toutes les combinaisons de select et ce que cela devrait produire ;-)
