### ISSUE TITLE
Incomplete behaviour and display of view "Assignments" when going directly there without going first to view "Questions".

### ISSUE THREAD

**Issue by thibaultestier** [bfritscher/sqlexplorer#8]
I copy here a message from Jean-Sébastien Monzani, describing the bug:

> Voici ce qui reproduit le bug (je viens de tester dans une fenêtre de navigation privée).
> 
> - se logger sur Moodle -> AAI -> choisir Unil dans la liste-> login AAI
> 
> - lancer SQL Explorer, se logger comme admin
> 
> - aller directement dans Assignments. Ouvrir un assignment. Cliquer maintenant sur Present (-> Bad request) ou sur View (-> réponses aux questions absentes).
> 
> - aller maintenant sur Questions, puis revenir sur Assignements -> les assignments marchent maintenant avec Present ou View.
> 
> Il semble qu'Assignement ait besoin de quelque chose dans sa lecture des questions que seul le clic sur Questions résoud.
> 
> Tadaaaaaaaaaaaaaaaaa :-D !!

**Comment by bfritscher** [comment]
Pas besoin de login / AAI.
C'est uniquement le fonctionnement de l'admin sqlexplorer basic auth.
Le problème c'est que l'authentification n'est pas explicitement demandée par les routes assignments qui sont utilisés à la fois pour admin et étudiant. Si le token existe il est envoyé avec la requête. Certaines routes de questions demandent explicitement l'authentification, c'est pour cela qu'ensuite cela fonctionne.

Il faut soit ajouter des routes spécifiques authentification
soit appeler une route avec auth, et ensuite appeler les autres, mais doit se faire dans cet ordre :-(

**Comment by bfritscher** [comment]
Ok fixed with login route guard prompting for password on all admin routes on client side.
